import streamlit as st
import pandas as pd
import data.tmdb_client as tmdb
from ui.components import render_card_grid, taste_profile_card
from storage.db import log_recommendations
from config import WATCH_HISTORY_PERSONAS


def _get_taste_profile(user_id: int, train_df: pd.DataFrame,
                        movies_df: pd.DataFrame) -> dict:
    user_ratings  = train_df[train_df["user_id"] == user_id]
    rated_movies  = movies_df[movies_df["movie_id"].isin(user_ratings["movie_id"])]
    merged        = rated_movies.merge(user_ratings[["movie_id", "rating"]], on="movie_id")

    genre_counts: dict[str, int] = {}
    for genres in rated_movies["genres"]:
        for g in (genres or []):
            genre_counts[g] = genre_counts.get(g, 0) + 1
    top_genres = sorted(genre_counts, key=genre_counts.get, reverse=True)[:3]

    years = merged["year"].dropna()
    years = pd.to_numeric(years, errors="coerce").dropna()
    if len(years):
        avg_year = years.mean()
        era = ("Classic (pre-1980)" if avg_year < 1980
               else "Modern (post-2000)" if avg_year >= 2000
               else "Mixed (1980–2000)")
    else:
        era = "Mixed"

    avg_rating = round(float(merged["rating"].mean()), 1) if len(merged) else 0.0

    last5 = (
        train_df[train_df["user_id"] == user_id]
        .sort_values("timestamp", ascending=False)
        .head(5)
        .merge(movies_df[["movie_id", "title", "year"]], on="movie_id")
    )

    return {
        "top_genres":  top_genres,
        "era":         era,
        "avg_rating":  avg_rating,
        "total_rated": len(user_ratings),
        "last5":       last5,
    }


def _enrich_recs(recs: list[tuple], movies_df: pd.DataFrame) -> list[dict]:
    lookup = movies_df.set_index("movie_id")
    enriched = []
    for movie_id, score in recs:
        if movie_id not in lookup.index:
            continue
        row   = lookup.loc[movie_id]
        title = str(row["title"])
        year  = row.get("year")
        year_int = int(year) if year and str(year).isdigit() else None
        try:
            result     = tmdb.search_movie(title, year_int)
            poster_url = tmdb.get_poster_url(result.get("poster_path") if result else None)
            tmdb_rating = float(result.get("vote_average", 0)) if result else 0.0
        except Exception:
            poster_url  = ""
            tmdb_rating = 0.0
        enriched.append({
            "movie_id":        movie_id,
            "title":           title,
            "year":            str(year_int) if year_int else "",
            "predicted_score": round(float(score), 2),
            "poster_url":      poster_url,
            "tmdb_rating":     tmdb_rating,
        })
    return enriched


def render(models: dict, meta: dict, session_id: str):
    st.markdown("### Find movies based on your watch history")
    st.markdown(
        '<p style="color:#aaa;font-size:13px;margin-bottom:12px;">'
        'Pick a movie fan — each is a real MovieLens user with a distinct taste. '
        'Recommendations are generated by Funk SVD from their rating history.'
        '</p>',
        unsafe_allow_html=True,
    )

    persona = st.selectbox(
        "Choose a movie fan",
        WATCH_HISTORY_PERSONAS,
        format_func=lambda p: f"{p['label']}  ·  {p['desc']}",
        key="wh_persona",
    )
    selected_uid = persona["user_id"]

    profile = _get_taste_profile(selected_uid, meta["train_df"], meta["movies_df"])
    taste_profile_card(profile["top_genres"], profile["era"],
                       profile["avg_rating"], profile["total_rated"])

    if not profile["last5"].empty:
        with st.expander("Last 5 movies watched", expanded=False):
            for _, row in profile["last5"].iterrows():
                yr = int(row["year"]) if row.get("year") and str(row["year"]).isdigit() else "?"
                st.markdown(
                    f'<span style="color:white;">▸ {row["title"]} ({yr})</span>',
                    unsafe_allow_html=True,
                )

    st.markdown("---")

    cache_key = f"wh_recs_{selected_uid}"
    if cache_key not in st.session_state:
        with st.spinner("Generating recommendations..."):
            # restrict candidates to the persona's signature genres, then
            # let Funk SVD rank the best films within them for this user
            sig = set(persona["genres"])
            allowed = {
                row["movie_id"]
                for _, row in meta["movies_df"].iterrows()
                if sig & set(row["genres"] or [])
            }
            raw_recs = models["funk_svd"].recommend(
                selected_uid, n=10, allowed_movie_ids=allowed
            )
            st.session_state[cache_key] = _enrich_recs(raw_recs, meta["movies_df"])
        log_recommendations(
            session_id, tab="watchhistory", method="funk_svd",
            recommendations=[(m["title"], m["predicted_score"])
                             for m in st.session_state[cache_key]],
            input_user_id=selected_uid,
        )

    enriched = st.session_state[cache_key]

    if not enriched:
        st.warning("No recommendations found for this user.")
        return

    genres_str = " · ".join(persona["genres"])
    st.markdown(
        f'<p style="color:#aaa;font-size:13px;margin-bottom:16px;">'
        f'Top picks for <b style="color:#E50914;">{persona["label"]}</b> — '
        f'Funk SVD ranking within their favourite genres ({genres_str})'
        f'</p>',
        unsafe_allow_html=True,
    )
    render_card_grid(enriched, cols=5)
