[theme]
base = "dark"
primaryColor = "#E50914"
backgroundColor = "#0F0F0F"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = false
port = 8501

[browser]
gatherUsageStats = false
